/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rbd.h"

//todo como vamos chamar as funções
//via menu terminal???
//result_1 retorna um ponteiro - verificar se é nulo
//result_2 em diante é um inteiro - 0 ou 1
//clnt - handler

int
main (int argc, char *argv[])
{
	CLIENT *clnt;
	int  *result_1;
	char *inicializar_1_arg;
	int  *result_2;
	char * insere_1_arg;
	int  *result_3;
	char * remove_1_arg;
	int  *result_4;
	char * busca_1_arg;
	char *host;
	int opcao = 0;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	clnt = clnt_create (host, RBDPROG, RDBVERS, "udp");
	
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	while (opcao == 0) {
		printf("Menu de opções:\n");
		printf("\n1- Inicializar\n 2- Inserir\n 3- Remover\n 4- Buscar\n 5-Sair\n\n");
		scanf("%d", &opcao);
		char* palavra;

		switch (opcao)
		{
			case 1:
				result_1 = inicializar();
				printf("INICIALIZADO!\n");
				break;
			case 2:
				printf("Informe a palavra:");
				scanf("%s", palavra);
				result_2 = insere(&palavra);
				if (result_2 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("PALAVRA INSERIDA!\n");
				}
				break;
			case 3:
				printf("Informe a palavra:");
				scanf("%s", palavra);
				result_3 = remover(&palavra);
				if (result_3 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("PALAVRA REMOVIDA!\n");
				}
				break;
			case 4:
				printf("Informe a palavra:");
				scanf("%s", palavra);
				result_4 = busca(&palavra);
				if (result_4 == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				} else {
					printf("PALAVRA ENCONTRADA!\n");
				}
				break;
			default:
				break;
		}
	}

	clnt_destroy (clnt);
	exit (0);
}
//gcc -o server rbd_sif.c rbd_svc.c rbd_srp.c rbd_xdr.c -I/usr/include/tirpc -ltirpc - compilacao de servidor
//gcc -o cliente rbd_cif.c rbd_clnt.c rbd_client.c rbd_xdr.c -I/usr/include/tirpc -ltirpc  - compilacao de cliente