/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rbd.h"


void
rbdprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *inicializar_1_arg;
	int  *result_2;
	char * insere_1_arg;
	int  *result_3;
	char * remove_1_arg;
	int  *result_4;
	char * busca_1_arg;

#ifndef	DEBUG
//consulta portmapper
//host - passado na main

	clnt = clnt_create (host, RBDPROG, RDBVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

//todo como vamos chamar as funções
//via menu terminal???
//result_1 retorna um ponteiro - verificar se é nulo
//result_2 em diante é um inteiro - 0 ou 1
//clnt - handler

	result_1 = inicializar_1((void*)&inicializar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = insere_1(&insere_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = remove_1(&remove_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = busca_1(&busca_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rbdprog_1 (host);

	//fazer nmenu aqui switch case
exit (0);
}
//gcc -o server rbd_sif.c rbd_svc.c rbd_srp.c rbd_xdr.c  - compilacao de servidor
//gcc -o cliente rbd_cif.c rbd_clnt.c rbd_client.c rbd_xdr.c  - compilacao de cliente